develop branch
willyfox07/pythonProject pull request #1
Opened 2021-06-16 13:23 UTC by willyfox07

2021-06-25 10:53 UTC, willyfox07 commented
я тут с коммитами переборщил) но вроде уже понял как делать так чтобы их не было так много

2021-06-28 06:25 UTC, inauros requested changes
1. Please, when you create PRs, name them in accordance with the current step.
2. In accordance with step 4 in Grow, you had to include a README file with details about the project goal in English.
2. In accordance with step 5 in Grow, you had to create a folder "documentation" at the root of your repository - this folder must include all files related to SRS
3. Date of Birth should be used instead of Hiring Date
4. For all negative cases (employee/department can't be updated/saved/removed, etc.), mockups also should be created.
5. please remove pythonProject file

2021-06-28 06:25 UTC, inauros commented on README.md
> +- Department - which department does the employee belong to.
The department field must be a dropdown, not text - you must allow associating employees to an existing (in the database) department.

2021-06-28 06:25 UTC, inauros commented on README.md
> +- User enters employee data and presses "Cancel" button;
I suppose, user should update, not enter the data

2021-06-28 06:25 UTC, inauros commented on README.md
> +
Wrong main scenario

2021-06-28 06:25 UTC, inauros commented on README.md
> +![Edit employee](/image/edit_employee.png)
For the edit scenario should be used another mockup (data should be pre-filled)

2021-06-28 06:25 UTC, inauros commented on README.md
> +- If the employee can be removed, a confirmation dialog is displayed;
Why "If"? Are there cases, when the employee can't be removed? If yes, please could you list them?

2021-06-28 06:25 UTC, inauros commented on README.md
> +![Edit employee](/image/delete_order.png)
As I can see on mockup, you are trying to remove order, not employee ;)

2021-06-28 06:25 UTC, inauros commented on README.md
> +- Location - where this department located.
the average salary column is missed

2021-06-28 06:25 UTC, inauros commented on README.md
> +- Application displays list of employees;
I suppose departments not employees

2021-06-28 06:25 UTC, inauros commented on README.md
> +**Filtering by location:**
1. I guess other fields should also be involved in filtering
2. how about sorting?

2021-06-28 06:25 UTC, inauros commented on README.md
> +
The same comments as for employees.

2021-06-28 06:25 UTC, inauros commented on README.md
> +![Edit department](/image/edit_department.png)
The same as for employees - please fix the mockup

2021-06-28 06:25 UTC, inauros commented on README.md
> +![Delete department](/image/delete_department.png)
Again, you are removing Order not department :)

2021-06-29 11:26 UTC, willyfox07 commented on README.md
> +"Employee Manager" s a web application designed for the management of employees and departments with these employees.
fixed

2021-06-29 11:26 UTC, willyfox07 commented on README.md
> +Applecation should provide:
fixed

2021-06-29 11:26 UTC, willyfox07 commented on README.md
> +- Updating list of depatrments;
fixed

2021-06-29 11:26 UTC, willyfox07 commented on README.md
> +- Filtering by hiring date for employees;
fixed

2021-06-29 11:26 UTC, willyfox07 commented on README.md
> +Pic.1.1 View the list of employees.
fixed

2021-06-29 11:52 UTC, willyfox07 commented on README.md
> +**Filtering by location:**
fixed

2021-06-29 12:00 UTC, willyfox07 commented on README.md
> +![Edit department](/image/edit_department.png)
fixed

2021-06-29 12:02 UTC, willyfox07 commented on README.md
> +![Delete department](/image/delete_department.png)
fixed

2021-06-29 15:04 UTC, willyfox07 commented on README.md
> +
Тут я не очень понимаю что мне нужно исправить)

2021-06-30 06:05 UTC, inauros commented on README.md
> +Pic.1.1 View the list of employees.
I still don't see the Salary column )

2021-06-30 10:15 UTC, willyfox07 commented on README.md
> +Pic.1.1 View the list of employees.
fixed

2021-07-01 11:29 UTC, willyfox07 commented on README.md
> +- Hiring date - date when employee was hired;
fixed

2021-07-01 11:36 UTC, willyfox07 commented on README.md
> +![Edit employee](/image/edit_employee.png)
fixed

2021-07-01 11:40 UTC, willyfox07 commented on README.md
> +- Department - which department does the employee belong to.
fixed

2021-07-01 11:46 UTC, willyfox07 commented on README.md
> +- User enters employee data and presses "Cancel" button;
fixed

2021-07-01 12:05 UTC, willyfox07 commented on README.md
> +![Edit employee](/image/delete_order.png)
fixed

2021-07-01 12:07 UTC, willyfox07 commented on README.md
> +- If the employee can be removed, a confirmation dialog is displayed;
fixed

2021-07-01 14:14 UTC, willyfox07 commented on README.md
> +- Location - where this department located.
fixed

2021-07-01 14:19 UTC, willyfox07 commented on README.md
> +
fixed

2021-07-01 14:20 UTC, willyfox07 commented on README.md
> +
fixed

2021-07-01 14:54 UTC, willyfox07 commented on README.md
> +- Location - where this department located.
fixed

2021-07-01 14:54 UTC, willyfox07 commented on README.md
> +
fixed

2021-07-01 15:30 UTC, willyfox07 commented on README.md
> +
fixed

2021-07-05 19:04 UTC, inauros approved these changes

2021-07-07 12:02 UTC, merged